name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

permissions:
  contents: read # for checkout

jobs:
  gates:
    name: Build, Test, Release
    runs-on: ubuntu-latest

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json', '**/.eslintrc.cjs', '**/.prettierrc.cjs') }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security audit (prod)
        run: npm run security-audit:prod

      - name: Security audit (dev)
        run: npm run security-audit:dev

      - name: Commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          failOnErrors: true

      - name: ESLint
        run: npm run lint -- --cache --cache-strategy content --cache-location ~/.cache/.eslintcache

      - name: Prettier
        run: npm run format -- --cache --cache-strategy content --cache-location ~/.cache/.prettiercache

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Generate GitHub Pages
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          npm run build:typedoc
          npm run test:coverage
          npm run build:storybook
          npm run build:docusaurus
          rm -rf gh-pages
          mkdir gh-pages
          touch ./gh-pages/.nojekyll
          mv ./typedoc ./gh-pages/typedoc
          mv ./coverage ./gh-pages/coverage
          mv ./storybook-static ./gh-pages/storybook
          mv ./docusaurus/build ./gh-pages/docs

      - name: Release
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
